Flask db
rohan-suresh/flaskProject pull request #1
Opened 2017-06-12 23:43 UTC by rohan-suresh

added get and post endpoint for database that interacts with ember client

2017-06-12 23:50 UTC, adrianlizarraga requested changes
@rohan-suresh Left you a few comments. Looks good!

2017-06-12 23:50 UTC, adrianlizarraga commented on app.py
> +
Remove this extra empty line

2017-06-12 23:50 UTC, adrianlizarraga commented on app.py
> +	print(user_id)
Remove print statements

2017-06-12 23:50 UTC, adrianlizarraga commented on app.py
> +def getEvents(zybook_code, user_id):
Our convention for `Ember` code is camelCase. However, for python code we use lower case and dashes for all variables and method names. Ex: `get_events`.

2017-06-12 23:50 UTC, adrianlizarraga commented on app.py
> +def getData(zybook_code, user_id):
Let's rename this method to something more descriptive like `get_user_zybook_events`

2017-06-12 23:50 UTC, adrianlizarraga commented on app.py
> +def postData(zybook_code):
Same here. I would recommend renaming to something like `record_zybook_event`

2017-06-12 23:50 UTC, adrianlizarraga commented on app.py
> +	#datetime.datetime.now().isoformat()
Let's remove commented lines from code.

2017-06-13 18:55 UTC, rohan-suresh commented on app.py
> +
resolved

2017-06-13 18:55 UTC, rohan-suresh commented on app.py
> +def getEvents(zybook_code, user_id):
resolved

2017-06-13 18:56 UTC, rohan-suresh commented on app.py
> +	print(user_id)
resolved

2017-06-13 18:57 UTC, rohan-suresh commented on app.py
> +def getData(zybook_code, user_id):
resolved

2017-06-13 18:57 UTC, rohan-suresh commented on app.py
> +def postData(zybook_code):
resolved

2017-06-13 18:57 UTC, rohan-suresh commented on app.py
> +	#datetime.datetime.now().isoformat()
resolved

2017-06-14 16:37 UTC, adrianlizarraga approved these changes

2017-06-14 23:31 UTC, merged